name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      img:
        description: "image to download, for instance, tensorflow/tensorflow"
        required: true
      img-new-name:
        description: "new Image name"
        required: true
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Login to ACR
        uses: aliyun/acr-login@v1
        with:
          login-server: https://${{ secrets.REGISTRY_URL }}
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
      - name: Build and push image
        env:
          IMG_NAME: ${{ github.event.inputs.img }}
          IMG_NEW_NAME: ${{ github.event.inputs.img-new-name }}
        run: |
          docker pull ${IMG_NAME}
          docker tag ${IMG_NAME} ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_NS }}/${IMG_NEW_NAME}
          docker push ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_NS }}/${IMG_NEW_NAME}
