name: Docker Image Sync Batch

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to ACR
        uses: aliyun/acr-login@v1
        with:
          login-server: https://${{ secrets.REGISTRY_URL }}
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
      - name: Build and push image
        run: |
          # 读取文件内容，逐行处理
          while IFS= read -r line; do
              # 根据斜杠分隔成两部分
              part1=$(echo "$line" | cut -d'/' -f1)
              part2=$(echo "$line" | cut -d'/' -f2)

              if [[ ! $line =~ / ]] ; then
                  part1=library
              fi
              # 输出分隔后的两部分内容（可选）
              echo "Part 1: $part1"
              echo "Part 2: $part2"
              
              docker pull ${part1}/${part2}
              docker tag ${part1}/${part2} ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_NS }}/${part1}-${part2}
              docker push ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_NS }}/${part1}-${part2}
          done < data.txt
